### PR TITLE
just Corecting

### PR DESCRIPTION
**Pull request by BlasterLink**
corect word that a bit wrong

### CODE REVIEW

**Comment by SpencerPark** [comment]
This is actually not a typo, `helloWorld` is a variable. It cannot be renamed to `Hello World`.

**Comment by BlasterLink** [comment]
:v sorry i just want to get on hacktoberfest

Pada tanggal Sel, 30 Okt 2018 pukul 03.29 Spencer Park <
notifications@github.com> menulis:

**Comment by BlasterLink** [comment]
Are you in ?

Pada tanggal Rab, 31 Okt 2018 pukul 05.19 rahmadi cahaya putra <
rahmadicahayaputra2@gmail.com> menulis:

**Comment by SpencerPark** [comment]
Oh haha, no worries. I just signed up. Thanks for the info!

**Pull request closed without merging**
